name: CI

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

permissions:
  pull-requests: write
  contents: read

jobs:
  commit-message-check:
    name: Commit Message Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_commit-message-check.yml@e3e801bdc0d696988d6fc331b6cf0d806b653abd
    secrets: inherit

  trailing-newline-check:
    name: Trailing Newline Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_trailing-newline-check.yml@e3e801bdc0d696988d6fc331b6cf0d806b653abd
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit

  golangci-lint:
    name: golangci-lint
    uses: valkyrjaio/.github/.github/workflows/_go-golangci-lint.yml@e3e801bdc0d696988d6fc331b6cf0d806b653abd
    with:
      paths: |
        ci:
          - '.github/ci/lint/**'
          - '.golangci.yml'
          - 'Makefile'
          - '.github/workflows/ci.yml'
        files:
          - '**/*.go'
          - 'go.mod'
          - 'go.sum'
          - '.golangci.yml'
          - 'Makefile'
          - '.github/ci/lint/**'
          - '.github/workflows/ci.yml'
    secrets: inherit

  test:
    name: Test
    uses: valkyrjaio/.github/.github/workflows/_go-test.yml@e3e801bdc0d696988d6fc331b6cf0d806b653abd
    with:
      paths: |
        ci:
          - '.github/ci/lint/**'
          - 'Makefile'
          - '.github/workflows/ci.yml'
        files:
          - '**/*.go'
          - 'go.mod'
          - 'go.sum'
          - 'Makefile'
          - '.github/ci/lint/**'
          - '.github/workflows/ci.yml'
    secrets: inherit
