name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_go-update-dependencies.yml@983fb2adea0987861f9ec402e6e7a13638119f2c
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root Module",   "directory": "."},
          {"name": "golangci-lint", "directory": ".github/ci/lint"}
        ]
