name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_go-update-dependencies.yml@1438ce03055b4ad8010e8dfd863aa85d07f122ad
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root Module",   "directory": "."},
          {"name": "golangci-lint", "directory": ".github/ci/lint"}
        ]
